services:
  - type: web
    name: methodus-backend
    env: python
    runtime: python
    plan: free
    region: oregon
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: YOUTUBE_API_KEY
        value: AIzaSyDkLvrDiw6qbvy7p9RaPQnWJqhM95ChrmU
      - key: GEMINI_API_KEY
        value: AIzaSyB5JWC4lODXV5OniP5hFqd1sJ_MJgpl49o

