services:
  - type: web
    name: methodus-backend
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        generateValue: true

